version: "3.4"
name: bookapi
services:
  mysql:
    image: mysql:9.2.0
    restart: always
    env_file:
      - ./.env
    volumes:
      - ../db/inserts.sql:/docker-entrypoint-initdb.d/dbInserts.sql
      - ../db/bookapi.sql:/docker-entrypoint-initdb.d/dbCreation.sql
      - data:/var/lib/mysql
    ports:
      - 3306:3306
  api:
    image: bookapi
    build:
      context: ../bookapi/
      dockerfile: ../devops/Dockerfile.api
    env_file: ./.env
    ports:
      - $SPRING_PORT:$SPRING_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
               "spring.datasource.url" : "jdbc:mysql://bookapi-mysql-1:3306/bookapi?serverTimezone=UTC",
               "spring.datasource.username" : "user",
               "spring.datasource.password" : "pass",
               "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",

                "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL8Dialect",
                "spring.jpa.hibernate.ddl-auto" : "update",
                "spring.jpa.show-sql" : "true",
               "server.port" : "$SPRING_PORT"
             }'
    depends_on:
      - mysql
    restart: always

  web:
    build:
      context: ../Bookapiweb/
      dockerfile: ../devops/Dockerfile.web
    volumes:
      - ../Bookapiweb:/var/www/html
    ports:
      - 8001:80
    depends_on:
      - mysql
      - api

volumes:
  data:
